services:

  database:
    image: postgis/postgis:15-3.3
    container_name: inspection_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: geoinfo
      POSTGRES_DB: gestion_inspections
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: inspection_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - ./backend/.env
    command: sh -c "sleep 10 && npm run start:prod"

  frontend:
    build: ./frontend
    container_name: inspection_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
